### ISSUE TITLE
RESET quantum keycode does not work with Teensy 3.6

### ISSUE THREAD

**Issue by ameyp** [kinx-project/kint#7]
I've modded my Advantage 1 with a Teensy 3.6 and the RESET [quantum keycode](https://beta.docs.qmk.fm/using-qmk/simple-keycodes/quantum_keycodes) doesn't seem to work. When I run `qmk flash` and qmk is at `Waiting for Teensy device... (hint: press the reset button)`, sending the RESET keycode with a keypress doesn't put the board in bootloader mode and I have to press the physical button to allow flashing to proceed.

**Comment by stapelberg** [comment]
Thanks for the report. I indeed never tested this, because I had just assumed that reset is only for restarting the keyboard, not for reprogramming it :) 

https://www.pjrc.com/teensy/jump_to_bootloader.html is relevant, but doesn’t contain an address for the Teensy 3.6.

Let me see if this might be an easy fix.

**Comment by stapelberg** [comment]
Looks like on the Teensy 3.x, we need to call the BKPT instruction: https://forum.pjrc.com/threads/30521-Rebooting-Teensy-(LC-3-0)-to-bootloader-without-Teensyduino

**Comment by stapelberg** [comment]
I think commit https://github.com/kinx-project/qmk_firmware/commit/bb8ab07b477b8de7175db24a04e1a3569028da98 might help, but can’t test it right now. Can you `git pull` in your branch, recompile, reflash, and try again?

**Comment by stapelberg** [comment]
Just had a chance to test, and with the commit, the QK_RESET keycode jumps to the bootloader for me :)

**Comment by ameyp** [comment]
Works for me too, thanks!

**Comment by lread** [comment]
Oh, this is cool, I can flash via my Teensy without having to press the button on the Teensy?

I think `RESET` might have since been renamed to `QK_BOOTLOADER` in [commit](https://github.com/qmk/qmk_firmware/commit/b45a037c7edcd9c1cfadceb69ed51e7d42aa58c1#diff-801585dcf530fa1c9c07e022ddd95783097bfda2f180da6889ba64d6d6e3042aR224).

**Comment by lread** [comment]
Oh. Interesting, I see `QK_BOOT` is now mapped to the `prgm` key in the default `keymap.c`.

**Comment by lread** [comment]
And it actually works! Noice! 

@stapelberg This is very handy, especially for folks who put the screws back in their keyboards! I'm happy to add a note to the README, if you agree that makes sense.

**Comment by stapelberg** [comment]
> @stapelberg This is very handy, especially for folks who put the screws back in their keyboards! I'm happy to add a note to the README, if you agree that makes sense.

Sure, I guess? This is a standard QMK feature, so a quick note with a link to their documentation should be sufficient.

**Comment by lread** [comment]
Thanks for the reply! Because my motivation was to get my failing Advantage2 working again, I came to your project first first and then learned a bit about QMK. Maybe other folks come in knowing about QMK first. Anyway, your video really helped me with understanding how to solder things up and then flash. But, after watching it, maybe I missed it, but I naively never realized I could press a keyboard key to flash. I'll add a wee tip for other poor sods like me.
